name: flopo-data-pipeline
channels:
  - conda-forge
dependencies:
  - python=3
  - regex
  - beautifulsoup4
  - lxml
  - luigi
  - plumbum
  - ijson
  - yajl
  - pip
  - pip:
    - git+https://github.com/hsci-r/flopo-formats
